export {default as Home } from './Home'
export {default as Class } from './Class'
export {default as Courses } from './Courses'
export {default as Lectures } from './Lectures'
export {default as Semester } from './Semester'
export {default as Students } from './Students'
export {default as EnrollLists } from './EnrollLists'